version: '3.8'

services:
  app:
    build: .
    container_name: adoptme-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - adoptme-net

  mongo:
    image: mongo:6.0
    container_name: adoptme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - adoptme-net

volumes:
  mongo-data:

networks:
  adoptme-net: