version: "3.8"

services:
  app:
    image: frbahamondes/adoptme-backend
    build: .
    container_name: adoptme-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - adoptme-net

networks:
  adoptme-net: